### ISSUE TITLE
Receiving a invalid message from Fleep causes adapter to stop working

### ISSUE THREAD

**Issue by jimeh** [anroots/hubot-fleep#10]
Hubot stops communicating with Fleep for us every few hours, the process is still up and working, it's just not talking with Fleep's servers anymore. Seems to be a JSON parsing error which causes it to happen, here's the debug log output:

```
2015-02-10T09:04:47.589261+00:00 app[web.1]: [Tue Feb 10 2015 09:04:47 GMT+0000 (UTC)] INFO Loading knowledge
2015-02-10T09:04:47.589337+00:00 app[web.1]: [Tue Feb 10 2015 09:04:47 GMT+0000 (UTC)] DEBUG Updating last seen event horizon to 37456
2015-02-10T09:04:47.589364+00:00 app[web.1]: [Tue Feb 10 2015 09:04:47 GMT+0000 (UTC)] DEBUG Response stream length 0, nothing to parse.
2015-02-10T09:04:47.588988+00:00 app[web.1]: [Tue Feb 10 2015 09:04:47 GMT+0000 (UTC)] DEBUG HTTPS response body:
2015-02-10T09:04:47.589387+00:00 app[web.1]: [Tue Feb 10 2015 09:04:47 GMT+0000 (UTC)] DEBUG Finished handling long poll response
2015-02-10T09:04:47.589412+00:00 app[web.1]: [Tue Feb 10 2015 09:04:47 GMT+0000 (UTC)] DEBUG Starting long poll request
2015-02-10T09:04:47.589438+00:00 app[web.1]: [Tue Feb 10 2015 09:04:47 GMT+0000 (UTC)] DEBUG Last event horizon from robot brain: 37456
2015-02-10T09:04:47.589469+00:00 app[web.1]: [Tue Feb 10 2015 09:04:47 GMT+0000 (UTC)] DEBUG Sending new POST request
2015-02-10T09:04:47.589526+00:00 app[web.1]: [Tue Feb 10 2015 09:04:47 GMT+0000 (UTC)] DEBUG Setting cookie: token_id=[...]
2015-02-10T09:04:47.589556+00:00 app[web.1]: [Tue Feb 10 2015 09:04:47 GMT+0000 (UTC)] DEBUG Setting ticket: [...]
2015-02-10T09:04:47.589609+00:00 app[web.1]: [Tue Feb 10 2015 09:04:47 GMT+0000 (UTC)] DEBUG Request options:
2015-02-10T09:04:47.589757+00:00 app[web.1]: [Tue Feb 10 2015 09:04:47 GMT+0000 (UTC)] DEBUG { agent: false,
2015-02-10T09:04:47.589758+00:00 app[web.1]:   hostname: 'fleep.io',
2015-02-10T09:04:47.589760+00:00 app[web.1]:   port: 443,
2015-02-10T09:04:47.589761+00:00 app[web.1]:   path: '/api/account/poll',
2015-02-10T09:04:47.589762+00:00 app[web.1]:   method: 'POST',
2015-02-10T09:04:47.589763+00:00 app[web.1]:   headers:
2015-02-10T09:04:47.589765+00:00 app[web.1]:    { Host: 'fleep.io',
2015-02-10T09:04:47.589766+00:00 app[web.1]:      'User-Agent': 'hubot-fleep/0.6',
2015-02-10T09:04:47.589767+00:00 app[web.1]:      'Content-Type': 'application/json',
2015-02-10T09:04:47.589769+00:00 app[web.1]:      Cookie: 'token_id=[...]',
2015-02-10T09:04:47.589770+00:00 app[web.1]:      'Content-Length': 96 } }
2015-02-10T09:04:48.025338+00:00 app[web.1]: [Tue Feb 10 2015 09:04:48 GMT+0000 (UTC)] DEBUG Got response from the server.
2015-02-10T09:04:48.028832+00:00 app[web.1]: [Tue Feb 10 2015 09:04:48 GMT+0000 (UTC)] ERROR SyntaxError: Unexpected token <
2015-02-10T09:04:48.028834+00:00 app[web.1]:   at Object.parse (native)
2015-02-10T09:04:48.028835+00:00 app[web.1]:   at IncomingMessage.<anonymous> (/app/node_modules/hubot-fleep/src/webRequest.coffee:68:9, <js>:83:23)
2015-02-10T09:04:48.028837+00:00 app[web.1]:   at IncomingMessage.emit (events.js:117:20)
2015-02-10T09:04:48.028838+00:00 app[web.1]:   at _stream_readable.js:944:16
2015-02-10T09:04:48.028839+00:00 app[web.1]:   at process._tickCallback (node.js:442:13)
2015-02-10T09:04:48.028840+00:00 app[web.1]:
```

_Sensitive info replaced with `[...]`._

**Comment by anroots** [comment]
Will investigate ASAP, but probably not sooner than the 2nd half of this week.

**Comment by anroots** [comment]
Reopen this (with additional debug info) if the problem reappears.
