### ISSUE TITLE
Lost connection to Fleep causes the adapter to hang

### ISSUE THREAD

**Issue by anroots** [anroots/hubot-fleep#8]
When connection to Fleep is temporarily reset (Fleep does deployment, network problems) the adapter becomes unresponsive

**Comment by anroots** [comment]
```
at /app/node_modules/hubot-fleep/src/fleepClient.coffee:39:7, <js>:74:16
» 11:43:22.420 2015-02-03 09:43:22.128626+00:00 app web.1 - - at ClientRequest.<anonymous> (/app/node_modules/hubot-fleep/src/webRequest.coffee:99:7, <js>:114:49)
» 11:43:22.420 2015-02-03 09:43:22.128627+00:00 app web.1 - - at ClientRequest.emit (events.js:95:17)
» 11:43:22.420 2015-02-03 09:43:22.128629+00:00 app web.1 - - at CleartextStream.socketCloseListener (http.js:1527:9)
» 11:43:22.494 2015-02-03 09:43:22.128631+00:00 app web.1 - - at CleartextStream.emit (events.js:95:17)
» 11:43:22.494 2015-02-03 09:43:22.128632+00:00 app web.1 - - at tls.js:694:10
» 11:43:22.494 2015-02-03 09:43:22.128634+00:00 app web.1 - - at process._tickCallback (node.js:442:13)
» 11:43:22.494 2015-02-03 09:43:22.128635+00:00 app web.1 - -
» 11:43:22.494 2015-02-03 09:43:22.128970+00:00 app web.1 - - [Tue Feb 03 2015 11:43:22 GMT+0200 (EET)] ERROR HTTPS request error: { [Error: socket hang up] code: 'ECONNRESET' }
» 11:43:22.495 2015-02-03 09:43:22.107008+00:00 app web.1 - - [Tue Feb 03 2015 11:43:22 GMT+0200 (EET)] ERROR HTTPS request error: { [Error: socket hang up] code: 'ECONNRESET' }
» 11:43:22.495 2015-02-03 09:43:22.129608+00:00 app web.1 - - [Tue Feb 03 2015 11:43:22 GMT+0200 (EET)] ERROR Error: socket hang up at createHangUpError (http.js:1477:15) at CleartextStream.socketOnEnd [as onend] (http.js:1573:23) at CleartextStream.onCryptoStreamEnd (tls.js:323:24) at CleartextStream.g (events.js:180:16) at CleartextStream.emit (events.js:117:20) at _stream_readable.js:944:16 at process._tickCallback (node.js:442:13) Exception
» 11:43:22.495 2015-02-03 09:43:22.129621+00:00 app web.1 - -
» 11:43:22.495 2015-02-03 09:43:22.129625+00:00 app web.1 - - [Tue Feb 03 2015 11:43:22 GMT+0200 (EET)] DEBUG Poll complete
» 11:43:22.495 2015-02-03 09:43:22.130633+00:00 app web.1 - - [Tue Feb 03 2015 11:43:22 GMT+0200 (EET)] ERROR TypeError: Cannot read property 'event_horizon' of undefined
» 11:43:22.495 2015-02-03 09:43:22.130635+00:00 app web.1 - - at FleepClient.module.exports.FleepClient.handleStreamEvents (/app/node_modules/hubot-fleep/src/fleepClient.coffee:86:5, <js>:118:15)
» 11:43:22.495 2015-02-03 09:43:22.130637+00:00 app web.1 - - at FleepClient.handleStreamEvents (/app/node_modules/hubot-fleep/src/fleepClient.coffee:1:1, <js>:3:61)
```
